include("../../../Configuration/InterfaceTheme.js");

var spectrumOptions = {
    scaleDb: 24,
    scaleOptionsDb: [12, 24, 36],
    minimumFrequencyHz: 20,
    maximumFrequencyHz: 20000,
    background: AnalyzerColor(InterfaceTheme.colors.background),
    grid: AnalyzerColor(InterfaceTheme.colors.track),
    majorGrid: AnalyzerColor(InterfaceTheme.colors.border),
    label: AnalyzerColor(InterfaceTheme.colors.textMuted),
    current: AnalyzerColor(InterfaceTheme.colors.secondaryAccent),
    reference: AnalyzerColor(InterfaceTheme.colors.primaryAccent),
    fit: AnalyzerColor(InterfaceTheme.colors.tertiaryAccent),
    total: AnalyzerColor(InterfaceTheme.colors.text),
    filter: AnalyzerColor(InterfaceTheme.colors.primaryAccent),
    handle: AnalyzerColor(InterfaceTheme.colors.text),
    linkedHandle: AnalyzerColor(InterfaceTheme.colors.textInactive),
    totalLineWidth: InterfaceTheme.geometry.controlLineWidth,
    currentLineWidth: InterfaceTheme.geometry.indicatorLineWidth,
    filterLineWidth: InterfaceTheme.geometry.indicatorLineWidth,
    handleRadius: 5,
    handleLineWidth: InterfaceTheme.geometry.controlLineWidth,
    neutralHandleOpacity: 0.45,
    inactiveHandleOpacity: 0.70,
    linkedHandleOpacity: 0.65,
    linkedHandleLineWidth: InterfaceTheme.geometry.borderLineWidth,
    linkedHandleSize: 4,
    handleHitRadius: 18,
    gainHandleX: 8,
    controlActive: AnalyzerColor(InterfaceTheme.states.selected.border),
    controlInactive: AnalyzerColor(InterfaceTheme.states.inactive.border),
    bottomPadding: 18,
    controlHeight: analyzerControlsOptions ? analyzerControlsOptions.controlHeight : 18,
    controlPadding: analyzerControlsOptions ? analyzerControlsOptions.controlPadding : 4,
    majorFrequencies: [100, 1000, 10000],
    minorFrequencies: [20, 50, 200, 500, 2000, 5000],
    dbStep: 12,
    labelSize: InterfaceTheme.typography.minimumSize,
    fontFamily: InterfaceTheme.typography.fontFamily,
    controlLineWidth: InterfaceTheme.geometry.borderLineWidth
};
